//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.17929。
// 
namespace Lucas
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "importAQISoap", Namespace = "http://envir.gov.cn")]
    public partial class importAQI : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;

        private System.Threading.SendOrPostCallback importHourlyAQIOperationCompleted;

        private System.Threading.SendOrPostCallback importHourlyAQI1OperationCompleted;

        private System.Threading.SendOrPostCallback importAQIForecastOperationCompleted;

        private System.Threading.SendOrPostCallback importAirExecSQLOperationCompleted;

        private System.Threading.SendOrPostCallback importAirDataSetOperationCompleted;

        /// <remarks/>
        public importAQI()
        {
            this.Url = "http://www.envir.gov.cn/aqiforseec/importAQI.asmx";
        }

        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;

        /// <remarks/>
        public event importHourlyAQICompletedEventHandler importHourlyAQICompleted;

        /// <remarks/>
        public event importHourlyAQI1CompletedEventHandler importHourlyAQI1Completed;

        /// <remarks/>
        public event importAQIForecastCompletedEventHandler importAQIForecastCompleted;

        /// <remarks/>
        public event importAirExecSQLCompletedEventHandler importAirExecSQLCompleted;

        /// <remarks/>
        public event importAirDataSetCompletedEventHandler importAirDataSetCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/HelloWorld", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld()
        {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
        }

        /// <remarks/>
        public string EndHelloWorld(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void HelloWorldAsync()
        {
            this.HelloWorldAsync(null);
        }

        /// <remarks/>
        public void HelloWorldAsync(object userState)
        {
            if ((this.HelloWorldOperationCompleted == null))
            {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }

        private void OnHelloWorldOperationCompleted(object arg)
        {
            if ((this.HelloWorldCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/importHourlyAQI", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool importHourlyAQI(string LST, int AQI, int itemID, string password)
        {
            object[] results = this.Invoke("importHourlyAQI", new object[] {
                    LST,
                    AQI,
                    itemID,
                    password});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginimportHourlyAQI(string LST, int AQI, int itemID, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("importHourlyAQI", new object[] {
                    LST,
                    AQI,
                    itemID,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndimportHourlyAQI(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void importHourlyAQIAsync(string LST, int AQI, int itemID, string password)
        {
            this.importHourlyAQIAsync(LST, AQI, itemID, password, null);
        }

        /// <remarks/>
        public void importHourlyAQIAsync(string LST, int AQI, int itemID, string password, object userState)
        {
            if ((this.importHourlyAQIOperationCompleted == null))
            {
                this.importHourlyAQIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportHourlyAQIOperationCompleted);
            }
            this.InvokeAsync("importHourlyAQI", new object[] {
                    LST,
                    AQI,
                    itemID,
                    password}, this.importHourlyAQIOperationCompleted, userState);
        }

        private void OnimportHourlyAQIOperationCompleted(object arg)
        {
            if ((this.importHourlyAQICompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importHourlyAQICompleted(this, new importHourlyAQICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/importHourlyAQI1", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool importHourlyAQI1(string LST, int AQI, int itemID, string rtType, string rtDisplay, string password)
        {
            object[] results = this.Invoke("importHourlyAQI1", new object[] {
                    LST,
                    AQI,
                    itemID,
                    rtType,
                    rtDisplay,
                    password});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginimportHourlyAQI1(string LST, int AQI, int itemID, string rtType, string rtDisplay, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("importHourlyAQI1", new object[] {
                    LST,
                    AQI,
                    itemID,
                    rtType,
                    rtDisplay,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndimportHourlyAQI1(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void importHourlyAQI1Async(string LST, int AQI, int itemID, string rtType, string rtDisplay, string password)
        {
            this.importHourlyAQI1Async(LST, AQI, itemID, rtType, rtDisplay, password, null);
        }

        /// <remarks/>
        public void importHourlyAQI1Async(string LST, int AQI, int itemID, string rtType, string rtDisplay, string password, object userState)
        {
            if ((this.importHourlyAQI1OperationCompleted == null))
            {
                this.importHourlyAQI1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportHourlyAQI1OperationCompleted);
            }
            this.InvokeAsync("importHourlyAQI1", new object[] {
                    LST,
                    AQI,
                    itemID,
                    rtType,
                    rtDisplay,
                    password}, this.importHourlyAQI1OperationCompleted, userState);
        }

        private void OnimportHourlyAQI1OperationCompleted(object arg)
        {
            if ((this.importHourlyAQI1Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importHourlyAQI1Completed(this, new importHourlyAQI1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/importAQIForecast", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string importAQIForecast(string foreContent, string splitCharacter, string password)
        {
            object[] results = this.Invoke("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginimportAQIForecast(string foreContent, string splitCharacter, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public string EndimportAQIForecast(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void importAQIForecastAsync(string foreContent, string splitCharacter, string password)
        {
            this.importAQIForecastAsync(foreContent, splitCharacter, password, null);
        }

        /// <remarks/>
        public void importAQIForecastAsync(string foreContent, string splitCharacter, string password, object userState)
        {
            if ((this.importAQIForecastOperationCompleted == null))
            {
                this.importAQIForecastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAQIForecastOperationCompleted);
            }
            this.InvokeAsync("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password}, this.importAQIForecastOperationCompleted, userState);
        }

        private void OnimportAQIForecastOperationCompleted(object arg)
        {
            if ((this.importAQIForecastCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importAQIForecastCompleted(this, new importAQIForecastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/importAirExecSQL", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool importAirExecSQL(string sql, string password)
        {
            object[] results = this.Invoke("importAirExecSQL", new object[] {
                    sql,
                    password});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginimportAirExecSQL(string sql, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("importAirExecSQL", new object[] {
                    sql,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndimportAirExecSQL(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void importAirExecSQLAsync(string sql, string password)
        {
            this.importAirExecSQLAsync(sql, password, null);
        }

        /// <remarks/>
        public void importAirExecSQLAsync(string sql, string password, object userState)
        {
            if ((this.importAirExecSQLOperationCompleted == null))
            {
                this.importAirExecSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAirExecSQLOperationCompleted);
            }
            this.InvokeAsync("importAirExecSQL", new object[] {
                    sql,
                    password}, this.importAirExecSQLOperationCompleted, userState);
        }

        private void OnimportAirExecSQLOperationCompleted(object arg)
        {
            if ((this.importAirExecSQLCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importAirExecSQLCompleted(this, new importAirExecSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://envir.gov.cn/importAirDataSet", RequestNamespace = "http://envir.gov.cn", ResponseNamespace = "http://envir.gov.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet importAirDataSet(string sql, string password)
        {
            object[] results = this.Invoke("importAirDataSet", new object[] {
                    sql,
                    password});
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginimportAirDataSet(string sql, string password, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("importAirDataSet", new object[] {
                    sql,
                    password}, callback, asyncState);
        }

        /// <remarks/>
        public System.Data.DataSet EndimportAirDataSet(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }

        /// <remarks/>
        public void importAirDataSetAsync(string sql, string password)
        {
            this.importAirDataSetAsync(sql, password, null);
        }

        /// <remarks/>
        public void importAirDataSetAsync(string sql, string password, object userState)
        {
            if ((this.importAirDataSetOperationCompleted == null))
            {
                this.importAirDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAirDataSetOperationCompleted);
            }
            this.InvokeAsync("importAirDataSet", new object[] {
                    sql,
                    password}, this.importAirDataSetOperationCompleted, userState);
        }

        private void OnimportAirDataSetOperationCompleted(object arg)
        {
            if ((this.importAirDataSetCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.importAirDataSetCompleted(this, new importAirDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void importHourlyAQICompletedEventHandler(object sender, importHourlyAQICompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importHourlyAQICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal importHourlyAQICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void importHourlyAQI1CompletedEventHandler(object sender, importHourlyAQI1CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importHourlyAQI1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal importHourlyAQI1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void importAQIForecastCompletedEventHandler(object sender, importAQIForecastCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importAQIForecastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal importAQIForecastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void importAirExecSQLCompletedEventHandler(object sender, importAirExecSQLCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importAirExecSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal importAirExecSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    public delegate void importAirDataSetCompletedEventHandler(object sender, importAirDataSetCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class importAirDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal importAirDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public System.Data.DataSet Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

