//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.17929。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="PushAQIOCSoap", Namespace="http://www.sepb.gov.cn")]
public partial class PushAQIOC : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloSEICOperationCompleted;
    
    private System.Threading.SendOrPostCallback importAirExecSQLOperationCompleted;
    
    private System.Threading.SendOrPostCallback importAirDataSetOperationCompleted;
    
    private System.Threading.SendOrPostCallback importAQIHourlyOperationCompleted;
    
    private System.Threading.SendOrPostCallback importAQIHourlyProOperationCompleted;
    
    private System.Threading.SendOrPostCallback importAQIHourlyPro1OperationCompleted;
    
    private System.Threading.SendOrPostCallback importAQIForecastOperationCompleted;
    
    /// <remarks/>
    public PushAQIOC() {
        this.Url = "http://10.101.59.20/AQIforSEIC/PushAQIOC.asmx";
    }
    
    /// <remarks/>
    public event HelloSEICCompletedEventHandler HelloSEICCompleted;
    
    /// <remarks/>
    public event importAirExecSQLCompletedEventHandler importAirExecSQLCompleted;
    
    /// <remarks/>
    public event importAirDataSetCompletedEventHandler importAirDataSetCompleted;
    
    /// <remarks/>
    public event importAQIHourlyCompletedEventHandler importAQIHourlyCompleted;
    
    /// <remarks/>
    public event importAQIHourlyProCompletedEventHandler importAQIHourlyProCompleted;
    
    /// <remarks/>
    public event importAQIHourlyPro1CompletedEventHandler importAQIHourlyPro1Completed;
    
    /// <remarks/>
    public event importAQIForecastCompletedEventHandler importAQIForecastCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/HelloSEIC", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloSEIC() {
        object[] results = this.Invoke("HelloSEIC", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloSEIC(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloSEIC", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloSEIC(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloSEICAsync() {
        this.HelloSEICAsync(null);
    }
    
    /// <remarks/>
    public void HelloSEICAsync(object userState) {
        if ((this.HelloSEICOperationCompleted == null)) {
            this.HelloSEICOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloSEICOperationCompleted);
        }
        this.InvokeAsync("HelloSEIC", new object[0], this.HelloSEICOperationCompleted, userState);
    }
    
    private void OnHelloSEICOperationCompleted(object arg) {
        if ((this.HelloSEICCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloSEICCompleted(this, new HelloSEICCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAirExecSQL", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool importAirExecSQL(string sql, string password) {
        object[] results = this.Invoke("importAirExecSQL", new object[] {
                    sql,
                    password});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAirExecSQL(string sql, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAirExecSQL", new object[] {
                    sql,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndimportAirExecSQL(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void importAirExecSQLAsync(string sql, string password) {
        this.importAirExecSQLAsync(sql, password, null);
    }
    
    /// <remarks/>
    public void importAirExecSQLAsync(string sql, string password, object userState) {
        if ((this.importAirExecSQLOperationCompleted == null)) {
            this.importAirExecSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAirExecSQLOperationCompleted);
        }
        this.InvokeAsync("importAirExecSQL", new object[] {
                    sql,
                    password}, this.importAirExecSQLOperationCompleted, userState);
    }
    
    private void OnimportAirExecSQLOperationCompleted(object arg) {
        if ((this.importAirExecSQLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAirExecSQLCompleted(this, new importAirExecSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAirDataSet", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet importAirDataSet(string sql, string password) {
        object[] results = this.Invoke("importAirDataSet", new object[] {
                    sql,
                    password});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAirDataSet(string sql, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAirDataSet", new object[] {
                    sql,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndimportAirDataSet(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void importAirDataSetAsync(string sql, string password) {
        this.importAirDataSetAsync(sql, password, null);
    }
    
    /// <remarks/>
    public void importAirDataSetAsync(string sql, string password, object userState) {
        if ((this.importAirDataSetOperationCompleted == null)) {
            this.importAirDataSetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAirDataSetOperationCompleted);
        }
        this.InvokeAsync("importAirDataSet", new object[] {
                    sql,
                    password}, this.importAirDataSetOperationCompleted, userState);
    }
    
    private void OnimportAirDataSetOperationCompleted(object arg) {
        if ((this.importAirDataSetCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAirDataSetCompleted(this, new importAirDataSetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAQIHourly", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string importAQIHourly(string LST, string AQIData, string password) {
        object[] results = this.Invoke("importAQIHourly", new object[] {
                    LST,
                    AQIData,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAQIHourly(string LST, string AQIData, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAQIHourly", new object[] {
                    LST,
                    AQIData,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndimportAQIHourly(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void importAQIHourlyAsync(string LST, string AQIData, string password) {
        this.importAQIHourlyAsync(LST, AQIData, password, null);
    }
    
    /// <remarks/>
    public void importAQIHourlyAsync(string LST, string AQIData, string password, object userState) {
        if ((this.importAQIHourlyOperationCompleted == null)) {
            this.importAQIHourlyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAQIHourlyOperationCompleted);
        }
        this.InvokeAsync("importAQIHourly", new object[] {
                    LST,
                    AQIData,
                    password}, this.importAQIHourlyOperationCompleted, userState);
    }
    
    private void OnimportAQIHourlyOperationCompleted(object arg) {
        if ((this.importAQIHourlyCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAQIHourlyCompleted(this, new importAQIHourlyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAQIHourlyPro", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string importAQIHourlyPro(string LST, string[] AQIData, string password) {
        object[] results = this.Invoke("importAQIHourlyPro", new object[] {
                    LST,
                    AQIData,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAQIHourlyPro(string LST, string[] AQIData, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAQIHourlyPro", new object[] {
                    LST,
                    AQIData,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndimportAQIHourlyPro(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void importAQIHourlyProAsync(string LST, string[] AQIData, string password) {
        this.importAQIHourlyProAsync(LST, AQIData, password, null);
    }
    
    /// <remarks/>
    public void importAQIHourlyProAsync(string LST, string[] AQIData, string password, object userState) {
        if ((this.importAQIHourlyProOperationCompleted == null)) {
            this.importAQIHourlyProOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAQIHourlyProOperationCompleted);
        }
        this.InvokeAsync("importAQIHourlyPro", new object[] {
                    LST,
                    AQIData,
                    password}, this.importAQIHourlyProOperationCompleted, userState);
    }
    
    private void OnimportAQIHourlyProOperationCompleted(object arg) {
        if ((this.importAQIHourlyProCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAQIHourlyProCompleted(this, new importAQIHourlyProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAQIHourlyPro1", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string importAQIHourlyPro1(string LST, string[] AQIData, string rtType, string rtDisplay, string password) {
        object[] results = this.Invoke("importAQIHourlyPro1", new object[] {
                    LST,
                    AQIData,
                    rtType,
                    rtDisplay,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAQIHourlyPro1(string LST, string[] AQIData, string rtType, string rtDisplay, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAQIHourlyPro1", new object[] {
                    LST,
                    AQIData,
                    rtType,
                    rtDisplay,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndimportAQIHourlyPro1(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void importAQIHourlyPro1Async(string LST, string[] AQIData, string rtType, string rtDisplay, string password) {
        this.importAQIHourlyPro1Async(LST, AQIData, rtType, rtDisplay, password, null);
    }
    
    /// <remarks/>
    public void importAQIHourlyPro1Async(string LST, string[] AQIData, string rtType, string rtDisplay, string password, object userState) {
        if ((this.importAQIHourlyPro1OperationCompleted == null)) {
            this.importAQIHourlyPro1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAQIHourlyPro1OperationCompleted);
        }
        this.InvokeAsync("importAQIHourlyPro1", new object[] {
                    LST,
                    AQIData,
                    rtType,
                    rtDisplay,
                    password}, this.importAQIHourlyPro1OperationCompleted, userState);
    }
    
    private void OnimportAQIHourlyPro1OperationCompleted(object arg) {
        if ((this.importAQIHourlyPro1Completed != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAQIHourlyPro1Completed(this, new importAQIHourlyPro1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.sepb.gov.cn/importAQIForecast", RequestNamespace="http://www.sepb.gov.cn", ResponseNamespace="http://www.sepb.gov.cn", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string importAQIForecast(string foreContent, string splitCharacter, string password) {
        object[] results = this.Invoke("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginimportAQIForecast(string foreContent, string splitCharacter, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndimportAQIForecast(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void importAQIForecastAsync(string foreContent, string splitCharacter, string password) {
        this.importAQIForecastAsync(foreContent, splitCharacter, password, null);
    }
    
    /// <remarks/>
    public void importAQIForecastAsync(string foreContent, string splitCharacter, string password, object userState) {
        if ((this.importAQIForecastOperationCompleted == null)) {
            this.importAQIForecastOperationCompleted = new System.Threading.SendOrPostCallback(this.OnimportAQIForecastOperationCompleted);
        }
        this.InvokeAsync("importAQIForecast", new object[] {
                    foreContent,
                    splitCharacter,
                    password}, this.importAQIForecastOperationCompleted, userState);
    }
    
    private void OnimportAQIForecastOperationCompleted(object arg) {
        if ((this.importAQIForecastCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.importAQIForecastCompleted(this, new importAQIForecastCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void HelloSEICCompletedEventHandler(object sender, HelloSEICCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloSEICCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloSEICCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAirExecSQLCompletedEventHandler(object sender, importAirExecSQLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAirExecSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAirExecSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAirDataSetCompletedEventHandler(object sender, importAirDataSetCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAirDataSetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAirDataSetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAQIHourlyCompletedEventHandler(object sender, importAQIHourlyCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAQIHourlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAQIHourlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAQIHourlyProCompletedEventHandler(object sender, importAQIHourlyProCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAQIHourlyProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAQIHourlyProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAQIHourlyPro1CompletedEventHandler(object sender, importAQIHourlyPro1CompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAQIHourlyPro1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAQIHourlyPro1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
public delegate void importAQIForecastCompletedEventHandler(object sender, importAQIForecastCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.17929")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class importAQIForecastCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal importAQIForecastCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

